#! /bin/bash

BKP_FILE="/tmp/cron-sum"

if [[ -f $BKP_FILE ]]; then
	sum=$(cat /etc/crontab | md5sum)
	old_sum=$(cat "$BKP_FILE")

	if [[ ! "$sum" = "$old_sum" ]]; then
		mail -s 'CRONTAB' root <<EOF
The /etc/crontab file changed
EOF
	fi
fi
cat /etc/crontab | md5sum > $BKP_FILE
