#! /bin/bash

BKP_FILE="/tmp/cron-sum"

if [[ -f $BKP_FILE ]]; then
	sum=$(cat /etc/crontab | md5sum)
	old_sum=$(cat "$BKP_FILE")

	if [[ ! "$sum" = "$old_sum" ]]; then
		mail -s 'CRONTAB' root <<EOF
The /etc/crontab file changed
EOF
	fi
fi
cat /etc/crontab | md5sum > $BKP_FILE

# To create an automated task to run this script:
# execute crontab -e
# This command opens a temp file containing all tasks for the current user
# Add this line to the file:
# 0 0 * * * PATH_TO_THE_SCRIPT
# save and quit
